# DEMO 1: IRIS (CLASSIFICATION)

In [1]:
# DATA: IRIS
#  predictors: 4D measurments of flowers.
#  response: 3 types of flowers.
path = '/Users/jacobsw/Desktop/IMPLEMENTATION_CAMP/CODE/OJO/DEEP_LEARNING/DATA/uci/iris/iris.csv'

In [2]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.cross_validation import cross_val_score, KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [3]:
# SET SEED
seed = 7
np.random.seed(seed)

In [5]:
# LOAD DATA
dataframe = pd.read_csv(path, header=None)
dataset = dataframe.values
X = dataset[:,0:4].astype(float)
Y = dataset[:,4]

In [7]:
dataframe.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [9]:
print X[:5], Y[:5]

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]] ['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [14]:
# CLASS-TAG ONE-HOT CONVERSION
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y) # int encoding.

In [15]:
encoded_Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
dummy_y = np_utils.to_categorical(encoded_Y) # one-hot conversion.
dummy_y[:5]

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [42]:
# MLP (FNN) BUILDING
#  4 input -> 4 hidden -> 3 output.
#     ^           ^           ^
#     |           |           |
#  w^t * x    relu(..)    sigmoid(..)
def baseline_model():
    model = Sequential()
    model.add(Dense(4, input_dim=4, init='normal', activation='relu'))
    model.add(Dense(3, init='normal', activation='sigmoid'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
estimator = KerasClassifier(build_fn=baseline_model, nb_epoch=20, batch_size=5, verbose=0)

In [23]:
%%time
# EVALUATION (CV)
kfold = KFold(n=len(X), n_folds=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print "Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100)

Accuracy: 67.33% (16.98%)
CPU times: user 11.9 s, sys: 77.2 ms, total: 12 s
Wall time: 12 s


# DEMO 2: SONAR (CLASSIFICATION)

In [29]:
# DATA: SONAR
#  predictors: 60 strength of return (sonar bouncing off surface).
#  response: 2 types, 'rock' or 'mine'.
path = '/Users/jacobsw/Desktop/IMPLEMENTATION_CAMP/CODE/OJO/DEEP_LEARNING/DATA/uci/sonar/sonar.csv'

In [31]:
import numpy as pn
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.cross_validation import cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline

In [32]:
# SET SEED
seed = 7
np.random.seed(seed)

In [35]:
# LOAD DATA
dataframe = pd.read_csv(path, header=None)
dataset = dataframe.values
X = dataset[:,0:60].astype(float)
Y = dataset[:,60]

In [36]:
dataframe.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...       51      52      53      54      55      56      57  \
0  0.2111  ...   0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...   0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...   0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...   0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...   0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59    60  
0  0.0090  0.0032  Rock  
1  0.0052  0.0044  Rock  
2  0.0095  0.0078  Rock  
3  0.0040  0.0117  Rock  
4  0.0107  0.0094  Rock  

[5 rows x 61 columns]

In [38]:
print X[:2], Y[:5]

[[ 0.02    0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
   0.2111  0.1609  0.1582  0.2238  0.0645  0.066   0.2273  0.31    0.2999
   0.5078  0.4797  0.5783  0.5071  0.4328  0.555   0.6711  0.6415  0.7104
   0.808   0.6791  0.3857  0.1307  0.2604  0.5121  0.7547  0.8537  0.8507
   0.6692  0.6097  0.4943  0.2744  0.051   0.2834  0.2825  0.4256  0.2641
   0.1386  0.1051  0.1343  0.0383  0.0324  0.0232  0.0027  0.0065  0.0159
   0.0072  0.0167  0.018   0.0084  0.009   0.0032]
 [ 0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
   0.2872  0.4918  0.6552  0.6919  0.7797  0.7464  0.9444  1.      0.8874
   0.8024  0.7818  0.5212  0.4052  0.3957  0.3914  0.325   0.32    0.3271
   0.2767  0.4423  0.2028  0.3788  0.2947  0.1984  0.2341  0.1306  0.4182
   0.3835  0.1057  0.184   0.197   0.1674  0.0583  0.1401  0.1628  0.0621
   0.0203  0.053   0.0742  0.0409  0.0061  0.0125  0.0084  0.0089  0.0048
   0.0094  0.0191  0.014   0.0049  0.0052  0.0044]] ['Rock' '

In [39]:
# CLASS-TAG CATEGORIZATION 
#  NB: NOT ONE-HOT FOR 2-CLASS TASKS)
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)

In [41]:
encoded_Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [47]:
# MLP (FNN) BUILDING
def create_baseline():
    model = Sequential()
    model.add(Dense(60, input_dim=60, init='normal', activation='relu'))
    model.add(Dense(1, init='normal', activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
estimator = KerasClassifier(build_fn=create_baseline, nb_epoch=20, batch_size=5, verbose=0)

In [48]:
%%time
# EVALUATION (CV)
kfold = StratifiedKFold(y=encoded_Y, n_folds=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, encoded_Y, cv=kfold)
print "Results: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100)

Results: 76.87% (7.85%)
CPU times: user 13.3 s, sys: 69.9 ms, total: 13.3 s
Wall time: 13.4 s


In [51]:
%%time
# STANDARDIZATION
np.random.seed(seed)
estimators = []
estimators.append(('standardized', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_baseline, nb_epoch=20, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(y=encoded_Y, n_folds=10, shuffle=True, random_state=seed)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print "Standardized: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100)

Standardized: 84.63% (5.52%)
CPU times: user 13.2 s, sys: 58.3 ms, total: 13.3 s
Wall time: 13.3 s


In [53]:
%%time
# SMALLER MLP??
#  less neurons in hidden, force model to pick out most important structure.
def create_smaller():
    model = Sequential()
    model.add(Dense(30, input_dim=60, init='normal', activation='relu'))
    model.add(Dense(1, init='normal', activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
np.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_smaller, nb_epoch=20, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(y=encoded_Y, n_folds=10, shuffle=True, random_state=seed)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print "Standardized: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100)

Standardized: 82.25% (4.11%)
CPU times: user 13.1 s, sys: 52 ms, total: 13.2 s
Wall time: 13.2 s


In [54]:
%%time
# DEEPER MLP??
#  more ways for model to extract key features and recombine them nonlinearly.
def create_larger():
    model = Sequential()
    model.add(Dense(60, input_dim=60, init='normal', activation='relu'))
    model.add(Dense(30, init='normal', activation='relu'))
    model.add(Dense(1, init='normal', activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
np.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_larger, nb_epoch=20, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(y=encoded_Y, n_folds=10, shuffle=True, random_state=seed)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print "Standardized: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100)

Standardized: 85.54% (4.32%)
CPU times: user 16.9 s, sys: 80.7 ms, total: 17 s
Wall time: 17 s


# DEMO 3: BOSTON HOUSING (REGRESSION)

In [60]:
# DATA: BOSTON HOUSEING
#  - crim – per capita crime rate by town.
#  - zn – proportion of residential land zoned for lots over 25,000 sq. ft.
#  - indus – proportion of non-retain business acres per town.
#  - chas - Charles River dummy variable (= 1 if tract bounds river; 0 otherwise).
#  - nox – nitrogen oxides concentration (parts per million).
#  - rm – average number of rooms per dwelling.
#  - age – proportion of owner-occupied units built prior to 1940.
#  - dis – weighted mean of distances to five Boston employment centers.
#  - rad – index of accessibility to radial highways
#  - tax – full-value property-tax rate per $10,000
#  - ptratio – pupil-teacher ratio by town
#  - black - 1000(Bk – 0.63)^2, where Bk is the proportion of blacks by town.
#  - lstat – lower status of the population (percent).
#  + medv – median value of owner-occupied homes in $1000s.

In [77]:
import numpy as pn
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.cross_validation import cross_val_score, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [78]:
# SET SEED
seed = 7
np.random.seed(seed)

In [79]:
# LOAD DATA
from sklearn.datasets import load_boston
data = load_boston()
X = data['data']
Y = data['target']
print X.shape, y.shape

(506, 13) (506,)


In [80]:
print X[:2], Y[:5]

[[  6.32000000e-03   1.80000000e+01   2.31000000e+00   0.00000000e+00
    5.38000000e-01   6.57500000e+00   6.52000000e+01   4.09000000e+00
    1.00000000e+00   2.96000000e+02   1.53000000e+01   3.96900000e+02
    4.98000000e+00]
 [  2.73100000e-02   0.00000000e+00   7.07000000e+00   0.00000000e+00
    4.69000000e-01   6.42100000e+00   7.89000000e+01   4.96710000e+00
    2.00000000e+00   2.42000000e+02   1.78000000e+01   3.96900000e+02
    9.14000000e+00]] [ 24.   21.6  34.7  33.4  36.2]


In [81]:
# MLP (FNN) BUILDING
#  NB: a. no transformation (e.g. one-hot, catgoricalization, etc.) needed.
#      b. no sigmoid output activation needed, we are interested in original numerical values.
#      c. rectifier activation on hidden preserved, it weeds out negatives, but doesn't touch positives.
def baseline_model():
    model = Sequential()
    model.add(Dense(13, input_dim=13, init='normal', activation='relu'))
    model.add(Dense(1, init='normal'))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model
estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=20, batch_size=5, verbose=0)

In [83]:
%%time
# EVALUATION (CV)
kfold = KFold(n=len(X), n_folds=10, random_state=seed)
results = cross_val_score(estimator, X, Y, cv=kfold)
print "Results: %.2f (%.2f) MSE" % (results.mean()*100, results.std()*100)

Results: 5173.39 (3949.24) MSE
CPU times: user 14.1 s, sys: 80.6 ms, total: 14.2 s
Wall time: 14.2 s


In [85]:
%%time
# STANDARDIZATION
np.random.seed(seed)
estimators = []
estimators.append(('standardized', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=baseline_model, nb_epoch=20, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n=len(X), n_folds=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print "Standardized: %.2f (%.2f) MSE" % (results.mean()*100, results.std()*100)

Standardized: 3792.49 (2855.98) MSE
CPU times: user 14.2 s, sys: 64.7 ms, total: 14.2 s
Wall time: 14.3 s


In [87]:
%%time
# DEEPER MLP??
def larger_model():
    model = Sequential()
    model.add(Dense(13, input_dim=13, init='normal', activation='relu'))
    model.add(Dense(6, init='normal', activation='relu'))
    model.add(Dense(1, init='normal'))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model
np.random.seed(seed)
estimators = []
estimators.append(('standardized', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=larger_model, nb_epoch=20, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n=len(X), n_folds=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print "Standardized: %.2f (%.2f) MSE" % (results.mean()*100, results.std()*100)

Standardized: 3190.93 (2998.78) MSE
CPU times: user 18.1 s, sys: 75.5 ms, total: 18.2 s
Wall time: 18.2 s


In [88]:
%%time
# WIDER MLP??
def wider_model():
    model = Sequential()
    model.add(Dense(20, input_dim=13, init='normal', activation='relu'))
    model.add(Dense(1, init='normal'))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model
np.random.seed(seed)
estimators = []
estimators.append(('standardized', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=wider_model, nb_epoch=20, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n=len(X), n_folds=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print "Standardized: %.2f (%.2f) MSE" % (results.mean()*100, results.std()*100)

Standardized: 3458.63 (2991.89) MSE
CPU times: user 14.3 s, sys: 66.5 ms, total: 14.4 s
Wall time: 14.4 s
